POST http://localhost:5000/api/posts
Content-Type: application/json

{
  "body":"New post",
  "userId": "6453d1cf5deac2c7a5df8a65"
}

GET http://localhost:5000/api/posts

GET http://localhost:5000/api/posts/6453cd7ca999816ab2445434

PATCH http://localhost:5000/api/posts/6453cd7ca999816ab2445434
Content-Type: application/json

{
  "body":"New HW"
}

DELETE http://localhost:5000/api/posts/6453cd7ca999816ab2445434
